import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		double sumToAverage = 0;
		int sum2 = 0;
		int sum3 = 0;
		int sum4 = 0;
		int sum = 0;
		String commonNum = "";
		for (int i = 1; i<=T; i++) {
			int b = 1;
			int g = 2;
			boolean girl = false;
			boolean boy = false;
			while (boy == false || girl == false) {
				int random = (int)(generator.nextDouble()*((2)+1));
				sum = sum + 1;
				sumToAverage = sumToAverage + 1;
				if (random == b) {
					boy = true;
				} else {
					girl = true;
				}
			}
			if (sum == 2) {
				sum2 = sum2 + 1;
			} else if (sum == 3) {
				sum3 = sum3 + 1;
			} else if (sum >= 4) {
				sum4 = sum4 + 1;
			}
			sum = 0;
		}
		sumToAverage = sumToAverage/T;
		int sumMax = Math.max(Math.max(sum2,sum3),sum4);
		if (sumMax == sum2) {
			commonNum = "2";
		} else if (sumMax == sum3) {
			commonNum = "3";
		} else if (sumMax == sum4) {
			commonNum = "4 or more";
		}
		System.out.println("Average: " + sumToAverage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + sum2);
		System.out.println("Number of families with 3 children: " + sum3);
		System.out.println("Number of families with 4 or more children: " + sum4);
		System.out.println("The most common number of children is " + commonNum + ".");
	}
}
